# Generated by Django 5.2.7 on 2025-10-31 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=150)),
                ('hsn_sac_code', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sgst_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('igst_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cess_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gst_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_stock', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('customer_view', models.CharField(default='Special', max_length=10)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='business_entity.businessentity')),
            ],
        ),
    ]
