# Generated by Django 5.2.7 on 2025-12-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='product_name',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='note',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='cost_price',
            new_name='discount_percent',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='min_stock',
            new_name='min_stock_product',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='mrp',
            new_name='mrp_baseprice',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cess_percent',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cgst_percent',
        ),
        migrations.RemoveField(
            model_name='item',
            name='hsn_sac_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='igst_percent',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sgst_percent',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unit',
        ),
        migrations.AddField(
            model_name='item',
            name='availability_status_service',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='brand_product',
            field=models.CharField(default='NA', max_length=150),
        ),
        migrations.AddField(
            model_name='item',
            name='cost_price_product',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='hsn_sac_code_product',
            field=models.CharField(blank=True, default='NA', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='kolkata/asia', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='quantity_product',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_product',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
