# Generated by Django 5.2.7 on 2025-12-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_product_name_item_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount_percent',
        ),
    ]
