# Generated by Django 5.2.7 on 2026-01-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_item_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity_product',
            field=models.IntegerField(),
        ),
    ]
