# Generated by Django 5.2.7 on 2026-01-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_item_quantity_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity_product',
            field=models.IntegerField(default=1),
        ),
    ]
