# Generated by Django 5.2.7 on 2026-01-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_item_quantity_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='mrp_baseprice',
            new_name='mrp_product',
        ),
        migrations.AddField(
            model_name='item',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_image_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_image_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_image_3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
