# Generated by Django 5.2.7 on 2026-01-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_mrp_baseprice_item_mrp_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='mrp_product',
            new_name='mrp_baseprice',
        ),
    ]
