# Generated by Django 5.2.7 on 2026-01-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_mrp_product_item_mrp_baseprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isShow',
            field=models.BooleanField(default=False),
        ),
    ]
