# Generated by Django 5.2.7 on 2026-01-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_item_isshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='includes_gst',
            field=models.BooleanField(default=False),
        ),
    ]
