# Generated by Django 5.2.7 on 2026-01-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_item_includes_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='max_order_quantity_product',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='min_order_quantity_product',
            field=models.IntegerField(default=1),
        ),
    ]
