# Generated by Django 5.2.7 on 2026-02-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_item_max_order_quantity_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
