# Generated by Django 5.2.7 on 2026-02-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_entity', '0008_businessentity_kyc_pan_id'),
        ('products', '0011_item_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('business', 'slug')},
        ),
    ]
