# Generated by Django 5.2.7 on 2026-02-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_item_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity_product',
            field=models.IntegerField(default=100),
        ),
    ]
