# Generated by Django 5.2.7 on 2026-03-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_item_quantity_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
