# Generated by Django 5.2.7 on 2026-04-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_item_category_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='includes_gst',
            new_name='price_includes_tax',
        ),
        migrations.RemoveField(
            model_name='item',
            name='gst_percent',
        ),
        migrations.AddField(
            model_name='item',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='item',
            name='tax_type',
            field=models.CharField(choices=[('GST', 'GST'), ('VAT', 'VAT'), ('SALES_TAX', 'Sales Tax'), ('NONE', 'No Tax')], default='GST', max_length=20),
        ),
    ]
