# Generated by Django 5.2.7 on 2026-04-06 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rename_includes_gst_item_price_includes_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price_includes_tax',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tax_type',
        ),
    ]
