# Generated by Django 5.2.7 on 2026-04-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_item_price_includes_tax_remove_item_tax_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='best_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
