# Generated by Django 5.2.7 on 2026-04-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_item_best_selling_item_trending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='best_selling',
            field=models.BooleanField(default=True),
        ),
    ]
