# Generated by Django 5.2.7 on 2026-04-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_item_best_selling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='best_selling',
            field=models.BooleanField(default=False),
        ),
    ]
