# Generated by Django 5.2.7 on 2026-05-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_item_barcode_alter_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Goods', 'Goods'), ('Service', 'Service')], max_length=20),
        ),
    ]
