# Generated by Django 5.2.7 on 2026-06-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_item_subcategory_item_subcategory_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_date', '-id']},
        ),
        migrations.AddField(
            model_name='item',
            name='has_variants',
            field=models.BooleanField(default=False, help_text='Enable variants like Color, Size, RAM etc.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='availability_status_service',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='customer_view',
            field=models.CharField(default='Special', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='mrp_baseprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity_product',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(blank=True, help_text='Optional. Example: Red / XL', max_length=255, null=True)),
                ('sku', models.CharField(help_text='Unique SKU within this business.', max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('min_stock', models.PositiveIntegerField(default=0)),
                ('mrp_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_order_quantity', models.PositiveIntegerField(default=1)),
                ('max_order_quantity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.item')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=100)),
                ('attribute_value', models.CharField(max_length=100)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.itemvariant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.itemvariant')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='itemvariant',
            constraint=models.UniqueConstraint(fields=('item', 'sku'), name='unique_variant_sku_per_item'),
        ),
        migrations.AddConstraint(
            model_name='variantattribute',
            constraint=models.UniqueConstraint(fields=('variant', 'attribute_name'), name='unique_attribute_per_variant'),
        ),
    ]
