# Generated by Django 5.2.7 on 2026-06-27 02:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_item_options_item_has_variants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariant',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
