# Generated by Django 5.2.7 on 2026-06-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_itemvariant_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
