# Generated by Django 5.2.7 on 2026-04-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoiceitem_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='total_gst',
            new_name='total_tax',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='gst_amount',
            new_name='tax_amount',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='gst_percent',
            new_name='tax_percent',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='taxable_amount',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='price_includes_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tax_type',
            field=models.CharField(default='GST', max_length=20),
            preserve_default=False,
        ),
    ]
