# Generated by Django 5.2.7 on 2026-04-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_rename_total_gst_invoice_total_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='item_name',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
