# Generated by Django 5.2.7 on 2025-12-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_invoice_net_payable_alter_invoice_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='net_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
