# Generated by Django 5.2.7 on 2026-01-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_invoice_net_payable_alter_invoice_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.IntegerField(),
        ),
    ]
