# Generated by Django 5.2.7 on 2026-03-23 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_entity', '0010_remove_businessentity_upi_qrcode_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('UPI', 'UPI'), ('GATEWAY', 'Gateway'), ('BOTH', 'Both'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('gateway_provider', models.CharField(blank=True, choices=[('', 'None'), ('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal')], max_length=20, null=True)),
                ('upi_qrcode_url', models.URLField(blank=True, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_webhook_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_merchant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_gateway_active', models.BooleanField(default=False)),
                ('is_upi_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_config', to='business_entity.businessentity')),
            ],
        ),
    ]
