# Generated by Django 5.2.7 on 2026-01-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_entity', '0005_remove_businessentity_entity_code_name_and_more'),
        ('customers', '0003_customer_otp_customer_otp_expiry_and_more'),
        ('order', '0002_cart_cartitem'),
        ('products', '0003_remove_item_discount_percent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('customer', 'business')},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'item')},
        ),
    ]
