# Generated by Django 5.2.7 on 2026-01-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_cart_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='asia', max_length=10),
            preserve_default=False,
        ),
    ]
