# Generated by Django 5.2.7 on 2026-01-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_cartitem_unique_together_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.IntegerField(),
        ),
    ]
