# Generated by Django 5.2.7 on 2026-02-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_cartitem_options_cartitem_created_at'),
        ('products', '0010_item_max_order_quantity_product_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'item'], name='order_carti_cart_id_752a11_idx'),
        ),
    ]
