# Generated by Django 5.2.7 on 2026-02-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_cartitem_order_carti_cart_id_752a11_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attachment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
