# Generated by Django 5.2.7 on 2026-04-07 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_customer_name_order_discount_amount_and_more'),
        ('products', '0016_remove_item_price_includes_tax_remove_item_tax_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_gst',
            new_name='total_tax',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total_value',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='gst_amount',
            new_name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='gst_percent',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_includes_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax_type',
            field=models.CharField(default='GST', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordered_items', to='products.item'),
        ),
    ]
