# Generated by Django 5.2.7 on 2026-06-28 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_entity', '0012_alter_businessentity_is_active'),
        ('customers', '0004_alter_customer_email_alter_customer_gstin_and_more'),
        ('order', '0016_alter_payment_status'),
        ('products', '0025_alter_variantimage_image_url'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cartitem',
            name='order_carti_cart_id_752a11_idx',
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.itemvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.itemvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_attributes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('RAZORPAY', 'Razorpay'), ('PAYPAL', 'PayPal')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'item', 'variant'], name='order_carti_cart_id_e08f2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('customer', 'business'), name='unique_customer_business_cart'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'item', 'variant'), name='unique_cart_item_variant'),
        ),
    ]
