# Generated by Django 5.2.7 on 2025-12-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('logo_bucket_url', models.URLField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_type', models.CharField(max_length=55)),
                ('gst_status', models.CharField(max_length=55)),
                ('gst_number', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('kyc_doc_type', models.CharField(max_length=20)),
                ('kyc_bucket_url', models.URLField(blank=True, null=True)),
                ('entity_code_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
