# Generated by Django 5.2.7 on 2025-12-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_entity', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessentity',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='businessentity',
            name='district',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='businessentity',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessentity',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
