# Generated by Django 5.2.7 on 2025-11-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_entity', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessentity',
            name='cloud_bucket_url',
            field=models.URLField(blank=True, help_text='Cloud bucket link for image', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='businessentity',
            name='entity_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
