# Generated by Django 5.2.7 on 2025-12-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_entity', '0003_businessentity_country_businessentity_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessentity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
