# Generated by Django 5.2.7 on 2026-01-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_entity', '0005_remove_businessentity_entity_code_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessentity',
            name='kyc_bucket_url',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessentity',
            name='logo_bucket_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
