# Generated by Django 5.2.7 on 2026-01-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_entity', '0006_alter_businessentity_kyc_bucket_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessentity',
            name='banner_1_url',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessentity',
            name='banner_2_url',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessentity',
            name='banner_3_url',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessentity',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessentity',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessentity',
            name='x_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessentity',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
