# Generated by Django 5.2.7 on 2026-01-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_entity', '0007_businessentity_banner_1_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessentity',
            name='kyc_pan_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
