# Generated by Django 5.2.7 on 2026-02-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_entity', '0008_businessentity_kyc_pan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessentity',
            name='upi_qrcode_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
