# Generated by Django 5.2.7 on 2026-03-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_entity', '0009_businessentity_upi_qrcode_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessentity',
            name='upi_qrcode_url',
        ),
        migrations.AddField(
            model_name='businessentity',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', max_length=10),
        ),
    ]
