# Generated by Django 5.2.7 on 2026-04-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_entity', '0010_remove_businessentity_upi_qrcode_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessentity',
            old_name='gst_number',
            new_name='tax_number',
        ),
        migrations.RenameField(
            model_name='businessentity',
            old_name='gst_status',
            new_name='tax_status',
        ),
        migrations.AddField(
            model_name='businessentity',
            name='price_includes_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessentity',
            name='tax_type',
            field=models.CharField(choices=[('GST', 'GST'), ('VAT', 'VAT'), ('SALES_TAX', 'Sales Tax'), ('NONE', 'No Tax')], default='GST', max_length=20),
        ),
    ]
