# Generated by Django 5.2.7 on 2026-06-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_entity', '0011_rename_gst_number_businessentity_tax_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessentity',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
