# Generated by Django 5.2.7 on 2025-12-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, default='statgrow123', max_length=128, null=True),
        ),
    ]
