# Generated by Django 5.2.7 on 2025-11-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gstin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
