# Generated by Django 5.2.7 on 2026-06-14 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_otp_customer_otp_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$', 'Enter a valid GSTIN')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
