# Generated by Django 5.2.7 on 2025-11-04 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='title',
        ),
    ]
